# Generated by Django 5.2.8 on 2025-11-26 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('contraseña', models.CharField(max_length=128)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_destino', models.CharField(max_length=100)),
                ('pais_destino', models.CharField(max_length=100)),
                ('fecha_ida', models.DateField()),
                ('fecha_vuelta', models.DateField()),
                ('punto_encuentro', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_creados', to='core.usuario')),
                ('participantes', models.ManyToManyField(related_name='viajes_en_los_que_participa', through='core.Participa', to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='participa',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.viaje'),
        ),
        migrations.AlterUniqueTogether(
            name='participa',
            unique_together={('usuario', 'viaje')},
        ),
    ]
