# Generated by Django 5.2.8 on 2025-12-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='punto_encuentro',
            new_name='direccion_encuentro',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='precio',
            new_name='precio_persona',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='estado',
        ),
        migrations.AddField(
            model_name='viaje',
            name='ciudad_origen',
            field=models.CharField(default='Madrid', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='estado_viaje',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='viaje',
            name='pais_origen',
            field=models.CharField(default='España', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='visibilidad',
            field=models.CharField(choices=[('PRIVADO', 'Privado'), ('PUBLICO', 'Público')], default='PUBLICO', max_length=10),
        ),
    ]
