# Generated by Django 5.2.8 on 2025-12-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_punto_encuentro_viaje_direccion_encuentro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='ali', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SolicitudAmistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to='core.usuario')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='core.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('emisor', 'receptor'), name='unique_solicitud_emisor_receptor'), models.CheckConstraint(condition=models.Q(('emisor', models.F('receptor')), _negated=True), name='no_autosolicitud')],
            },
        ),
    ]
