# Generated by Django 5.2.8 on 2025-12-30 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_username_solicitudamistad'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to='core.usuario')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_recibidas', to='core.usuario')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='core.viaje')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('viaje', 'receptor'), name='unique_invitacion_por_viaje_receptor'), models.CheckConstraint(condition=models.Q(('emisor', models.F('receptor')), _negated=True), name='no_autoinvitacion')],
            },
        ),
    ]
