# Generated by Django 5.2.8 on 2026-01-27 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invitacionviaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Chat del viaje', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_chat_creados', to='core.usuario')),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_chat', to='core.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeGrupoChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_grupo', to='core.usuario')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.grupochat')),
            ],
            options={
                'ordering': ['fecha_envio'],
            },
        ),
    ]
