# Generated by Django 5.2.8 on 2026-01-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_grupochat_mensajegrupochat'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='itinerario_publico',
            field=models.TextField(blank=True, default=''),
        ),
    ]
