# Generated by Django 5.2.8 on 2026-02-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_viaje_itinerario_publico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_pagados', to='core.usuario')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='core.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='GastoSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='core.gasto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas_gastos', to='core.usuario')),
            ],
            options={
                'unique_together': {('gasto', 'usuario')},
            },
        ),
    ]
