# Generated by Django 5.2.8 on 2026-02-19 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gasto_gastosplit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='gasto',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='gastosplit',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits_gastos', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='ParticipanteGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.gasto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_en_gastos', to='core.usuario')),
            ],
            options={
                'unique_together': {('gasto', 'usuario')},
            },
        ),
    ]
